pipeline {
    agent any

    stages {
        stage('Git') {
            steps {
                git branch: 'main', credentialsId: 'e7574c24-0a42-4dd7-a011-293bea349028', url: 'https://github.com/Lepisok/devops-netology'
            }
        }
        stage('Prepare molecule') {
            steps {
                sh '''pip3 install --upgrade requests==2.23.0
                ansible-galaxy collection install community.docker
                pip3 install molecule molecule-docker'''
            }
        }
        stage('Molecule') {
            steps {
                sh '''cd 3_CI_monitoring_and_settings_management/09-ci-04-jenkins/mnt-homeworks-ansible/roles/vector-role/
                molecule test'''
            }
        }
    }
}
