apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user
  namespace: user
subjects:
- kind: User
  name: user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: user
  apiGroup: rbac.authorization.k8s.io