apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-volumes
  labels:
    app: multitool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command: ['sh', '-c', 'while true; do echo "Hello world!" >> /tmp/1.txt; sleep 5; done;']
      - name: multitool
        image: praqma/network-multitool:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PORT
          value: "8080"
        volumeMounts: 
        - name: volume
          mountPath: /tmp
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pvc-vol
      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-vol
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  hostPath:
     path: /home
  persistentVolumeReclaimPolicy: Delete

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G