apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  labels:
    app: nginx-multitool
  namespace: app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-multitool
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:1.29
        imagePullPolicy: IfNotPresent
      - name: multitool
        image: praqma/network-multitool:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PORT
          value: "8080"