{
 "title": "My_dashboard",
 "time": { "from": "2023-03-25T16:20:32.026Z", "to": "2023-03-25T17:13:08.406Z" },
 "panels": [
  {
   "title": "Количество места на файловой системе ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_files_free{device=\"/dev/sda3\",fstype=\"ext4\",instance=\"node-exporter:9100\",job=\"node\"}\t",
     "legendFormat": "/dev/sda3"
    }
   ]
  },
  {
   "title": "Утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "MemFree",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\",job=\"node\"}",
     "legendFormat": "MemFree"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\n\r\nnode_load1{instance=\"node-exporter:9100\",job=\"node\"}",
     "legendFormat": "CPULA 1 min"
    },
    {
     "expr": "node_load5{instance=\"node-exporter:9100\",job=\"node\"}",
     "legendFormat": "CPULA 5 min"
    },
    {
     "expr": "node_load15{instance=\"node-exporter:9100\",job=\"node\"}",
     "legendFormat": "CPULA 15 min"
    }
   ]
  }
 ]
}