apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: default
spec:
  ports:
  - name: nginx-nodeport
    port: 80
    protocol: TCP
    nodePort: 32200 
  selector:
    app: nginx-multitool
  type: NodePort