apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  labels:
    app: nginx-multitool
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        imagePullPolicy: IfNotPresent
      - name: multitool
        image: praqma/network-multitool:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool
  namespace: default
spec:
  ports:
  - name: nginx-service
    port: 9001
    targetPort: 80
  - name: multitool-service
    port: 9002
    targetPort: 8080
  selector:
    app: nginx-multitool

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multitool-pod
  name: multitool-pod
  namespace: default
spec:
  containers:
  - image: praqma/network-multitool:latest
    name: multitool-pod
    imagePullPolicy: IfNotPresent
    env:
    - name: HTTP_PORT
      value: "9300"
