---
all:
  hosts:
    sonar-01:
      ansible_host: 158.160.41.60
    nexus-01:
      ansible_host: 158.160.62.226
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: lepis