---
all:
  hosts:
    sonar-01:
      ansible_host: 158.160.47.42
    nexus-01:
      ansible_host: 130.193.50.175
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: lepis