apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-volumes
  labels:
    app: multitool
  namespace: default
spec:
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PORT
          value: "8080"
        volumeMounts: 
        - name: volume
          mountPath: /multitool
      volumes:
        - name: volume
          hostPath:
            path: /var/log