version: '3'

services:
  elasticsearch-warm:
    image: elasticsearch:7.17.9
    container_name: elasticsearch-warm
    environment:
      - node.name=elasticsearch-warm
      - cluster.name=elasticsearch-cluster
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-warm
      - discovery.seed_hosts=elasticsearch-hot
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata_warm:/usr/share/elasticsearch/data
    networks:
      - elk

  elasticsearch-hot:
    image: elasticsearch:7.17.9
    container_name: elasticsearch-hot
    environment:
      - node.name=elasticsearch-hot
      - cluster.name=elasticsearch-cluster
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-warm
      - discovery.seed_hosts=elasticsearch-warm
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata_hot:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9200
    depends_on:
      - elasticsearch-warm
    networks:
      - elk

  kibana:
    image: kibana:7.17.9
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch-hot:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch-hot:9200","http://elasticsearch-warm:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-hot
      - elasticsearch-warm
    networks:
      - elk

  logstash:
    image: logstash:7.17.9
    container_name: logstash
    volumes:
      - ./config/logstash.conf:/etc/logstash/conf.d/logstash.conf:Z
      - ./config/logstash.yml:/opt/logstash/config/logstash.yml:Z
    ports:
      - "5046:5046"
      - "5044:5044"
    depends_on:
      - elasticsearch-hot
      - elasticsearch-warm
    networks:
      - elk

  filebeat:
    image: "elastic/filebeat:7.17.9"
    container_name: filebeat
    user: root
    command:
      - "--strict.perms=false"
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logstash
    networks:
      - elk

  some_application:
    image: library/python:3.9-alpine
    container_name: some_app
    volumes:
      - ./pinger/run.py:/opt/run.py:Z
    entrypoint: python3 /opt/run.py

volumes:
  esdata_warm:
  esdata_hot:

networks:
  elk:
    driver: bridge