apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: applications
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: applications
  template:
    metadata:
      labels:
        app: applications
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        imagePullPolicy: IfNotPresent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: applications
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applications
  template:
    metadata:
      labels:
        app: applications
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: applications
  namespace: default
spec:
  ports:
  - name: nginx-service
    port: 9001
    targetPort: 80
  - name: multitool-service
    port: 9002
    targetPort: 8080
  selector:
    app: applications
