apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: nginx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: multitool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HTTP_PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-srv-front
  namespace: default
spec:
  ports:
  - name: nginx-srv
    port: 9001
    targetPort: 80
  selector:
    app: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: multitool-srv-back
  namespace: default
spec:
  ports:
  - name: multitool-srv
    port: 9002
    targetPort: 8080
  selector:
    app: multitool

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: localhost
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: multitool-srv-back
            port: 
              name: multitool-srv
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: nginx-srv-front
            port: 
              name: nginx-srv